language: node_js

node_js:
  - '9'

sudo: false

branches:
  only:
  - master

install:
  - npm install
  - (cd e2e ; npm install)

script:
  - npm run compile
  - npm run e2e
  - npm run lint

after_failure:
  - cat e2e/server-fixture/log.txt